spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: classpath:dev/docker-compose.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:dev/data.sql
  mvc:
    log-request-details: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer_uri: ${ISSUER_URI}

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
