server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: reservapp-api # TODO: Hide
            client-secret: reservapp-password # TODO: Hide
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: http://accounts:8081/accounts/api-v1 # TODO: Hardcoded
