server:
  port: 8080
#  http2:
#    enabled: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations: # TODO: Tune this
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
        add-to-simple-url-handler-mapping: true

  mvc:
    log-request-details: true

  graphql:
    graphiql:
      enabled: true
