INSERT INTO business (id, owner_sub, active)
VALUES (1, 'ownerSub', true),
       (2, 'ownerSub', true),
       (3, 'ownerSub', true),
       (4, 'ownerSub', true),
       (5, 'ownerSub', true),
       (6, 'ownerSub', true),
       (7, 'ownerSub', true),
       (8, 'ownerSub', true),
       (9, 'ownerSub', true),
       (10, 'ownerSub', true),
       (11, 'ownerSub', true),
       (12, 'ownerSub', true),
       (13, 'ownerSub', true),
       (14, 'ownerSub', true),
       (15, 'ownerSub', false);

INSERT INTO service (business_id, name, active, description)
VALUES
    (1, 'cog an bol torture', true, 'Experience the ultimate relaxation with our innovative cog and bolt torture techniques.'),
    (2, 'bebr creation', true, 'Unlock your inner creativity with our bespoke bebr creation service.'),
    (1, 'blink on ya', true, NULL),
    (3, 'jelly beanssss', true, 'Indulge your sweet tooth with our premium jelly beanssss selection.'),
    (2, 'goofy ahh cut', true, 'Transform your look with our signature goofy ahh cut - bold and unconventional.'),
    (2, 'akwodawkd', false, NULL),
    (2, 'whirligig therapy', true, 'Embrace the whirligig therapy for a unique and exhilarating experience.'),
    (2, 'plonk n\' plop', true, NULL),
    (2, 'gobbledygook coaching', true, 'Master the art of gobbledygook with our personalized coaching sessions.'),
    (2, 'zippity zap massage', true, 'Feel the tension melt away with our zippity zap massage, a fusion of ancient techniques and modern innovation.'),
    (2, 'artisanal kale massage', true, NULL),
    (2, 'avocado facial peel', true, 'Rejuvenate your skin with our avocado facial peel, because who needs chemicals when you have avocados?'),
    (2, 'cosmic energy alignment', true, 'Balance your chakras and align your cosmic energy with our transcendental cosmic energy alignment service.'),
    (2, 'funky chicken dance therapy', true, NULL),
    (2, 'zen garden manicure', true, 'Find inner peace while getting your nails done with our zen garden manicure.'),
    (2, 'laughter yoga', true, NULL),
    (2, 'bubble wrap popping session', true, 'Relieve tension and anxiety by popping bubbles in our therapeutic bubble wrap popping session.'),
    (2, 'unicorn horn polishing', true, 'Add some sparkle to your life with our unicorn horn polishing service.'),
    (3, 'synchronized swimming lessons', true, 'Dive into elegance and grace with our synchronized swimming lessons.'),
    (1, 'cosmic latte tasting', true, 'Expand your palate with our cosmic latte tasting experience, where each sip is a journey through the universe.');
