INSERT INTO business (id, owner_sub, active)
VALUES (1, 'realownerowningstuff@mail.ru', true),
       (2, 'realownerowningstuff@mail.ru', true),
       (3, 'realownerowningstuff@mail.ru', true),
       (4, 'realownerowningstuff@mail.ru', true),
       (5, 'realownerowningstuff@mail.ru', true),
       (6, 'realownerowningstuff@mail.ru', true),
       (7, 'realownerowningstuff@mail.ru', true),
       (8, 'realownerowningstuff@mail.ru', true),
       (9, 'realownerowningstuff@mail.ru', true),
       (10, 'realownerowningstuff@mail.ru', true),
       (11, 'realownerowningstuff@mail.ru', true),
       (12, 'realownerowningstuff@mail.ru', true),
       (13, 'realownerowningstuff@mail.ru', true),
       (14, 'realownerowningstuff@mail.ru', true),
       (15, 'realownerowningstuff@mail.ru', false);

INSERT INTO service (business_id, name, active, description, picture_url)
VALUES
    (1, 'cog an bol torture', true, 'Experience the ultimate relaxation with our innovative cog and bolt torture techniques.', 'https://class-tour.com/wp-content/uploads/e/1/c/e1c00cbb019b29ec97c44a133cf8a361.jpeg'),
    (2, 'aboba creation', true, 'Unlock your inner creativity with our bespoke aboba creation service.', 'https://sportishka.com/uploads/posts/2022-11/1667532417_7-sportishka-com-p-palandoken-gornolizhnii-kurort-vkontakte-7.jpg'),
    (1, 'blink on ya', true, NULL, 'https://lukasamara.ru/images/site/0291.jpg'),
    (3, 'jelly beanssss', true, 'Indulge your sweet tooth with our premium jelly beanssss selection.', 'https://inforen.ru/wp-content/uploads/2020/02/12-1.jpg'),
    (2, 'goofy ahh cut', true, 'Transform your look with our signature goofy ahh cut - bold and unconventional.', 'https://www.eden-tour.ru/wp-content/uploads/2020/08/Carlton-St-Moriz-3.jpg'),
    (2, 'akwodawkd', false, NULL, 'https://thailand-good.ru/wp-content/uploads/2/1/9/21970b1fbca81f9954275082ed2fcdef.jpeg'),
    (2, 'whirligig therapy', true, 'Embrace the whirligig therapy for a unique and exhilarating experience.', 'https://center-tur.ru/wp-content/uploads/2019/12/tur-v-Avstriyu.jpg'),
    (2, 'plonk n\' plop', true, NULL, 'https://static.tildacdn.com/tild3866-6330-4362-b339-663033616333/_2021-09-20_170614.png'),
    (2, 'gobbledygook coaching', true, 'Master the art of gobbledygook with our personalized coaching sessions.', 'https://akpp-otvet.ru/wp-content/uploads/2018/01/termalnye-kurorty-vengrii.jpg'),
    (2, 'zippity zap massage', true, 'Feel the tension melt away with our zippity zap massage, a fusion of ancient techniques and modern innovation.', 'https://sportishka.com/uploads/posts/2022-11/1667495906_6-sportishka-com-p-gornie-kurorti-yevropi-krasivo-7.jpg'),
    (2, 'artisanal kale massage', true, NULL, 'https://thelawofattraction.ru/wp-content/uploads/e/d/a/eda9c2e15d275245a1bfe90ef9dca727.jpeg'),
    (2, 'avocado facial peel', true, 'Rejuvenate your skin with our avocado facial peel, because who needs chemicals when you have avocados?', 'https://sportishka.com/uploads/posts/2022-08/1661401536_10-sportishka-com-p-gornolizhnie-kurorti-shveitsarii-alpi-kras-21.jpg'),
    (2, 'cosmic energy alignment', true, 'Balance your chakras and align your cosmic energy with our transcendental cosmic energy alignment service.', 'https://sportishka.com/uploads/posts/2022-11/thumbs/1667476272_60-sportishka-com-p-lizhnie-kurorti-yevropi-vkontakte-63.jpg'),
    (2, 'funky chicken dance therapy', true, NULL, 'https://sportishka.com/uploads/posts/2023-11/1701315939_sportishka-com-p-kurorti-yevropi-pinterest-6.jpg'),
    (2, 'zen garden manicure', true, 'Find inner peace while getting your nails done with our zen garden manicure.', 'https://sportishka.com/uploads/posts/2023-11/1701300119_sportishka-com-p-samie-luchshie-kurorti-vkontakte-56.jpg'),
    (2, 'laughter yoga', true, NULL, 'https://traveltimes.ru/wp-content/uploads/2021/05/sea1.jpg'),
    (2, 'bubble wrap popping session', true, 'Relieve tension and anxiety by popping bubbles in our therapeutic bubble wrap popping session.', 'https://wallpapersgood.ru/wallpapers/main/201339/fdc8d335be27aa3.jpg'),
    (2, 'unicorn horn polishing', true, 'Add some sparkle to your life with our unicorn horn polishing service.', 'https://moretraveler.com/wp-content/uploads/2023/09/sa-24.jpg'),
    (3, 'synchronized swimming lessons', true, 'Dive into elegance and grace with our synchronized swimming lessons.', 'https://sportishka.com/uploads/posts/2022-03/1646923096_3-sportishka-com-p-gornolizhnie-kurorti-yevropi-turizm-krasiv-3.jpg'),
    (1, 'cosmic latte tasting', true, 'Expand your palate with our cosmic latte tasting experience, where each sip is a journey through the universe.', 'https://fotorelax.ru/wp-content/uploads/2016/06/Colorful-Amalfi-coast-26.jpg');
