version: '4.27'
services:
  staff-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: staff-db
    ports:
      - "3309:3306"
    volumes:
      - staff-db-data:/var/lib/mysql

volumes:
  staff-db-data:
