spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: classpath:dev/docker-compose.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:dev/data.sql
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE