spring:
  profiles:
    active: @spring.profiles.active@
#  jpa:
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      schema-locations: classpath:/schema.sql
#      mode: always
server:
  http2:
    enabled: true
  servlet:
    context-path: /api-v1