version: '4.27'
services:
  schedule-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: schedule-db
    ports:
      - "3306:3306"
    volumes:
      - schedule-db-data:/var/lib/mysql

volumes:
  schedule-db-data:
