version: '4.27'
services:
  schedule-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'schedule-pass'
      MONGO_INITDB_DATABASE: 'schedule-db'
    ports:
      - '27017:27017'
    volumes:
      - schedule-db-data:/data/db
    networks:
      - schedule-network

volumes:
  schedule-db-data:
