INSERT INTO business (name, owner_sub, description, active)
VALUES ('ABC Company', 'bebr1@mail.ru', 'Laugh away your worries with our revolutionary whoopee cushion therapy.', true),
       ('XYZ Corporation', 'bebr1@mail.ru', 'Experience the thrill of the flip with our flapjack flip service - guaranteed to impress.', true),
       ('123 Enterprises', 'bebr1@mail.ru', 'Unleash your inner beauty with our mumbo jumbo makeover, where nonsense meets elegance.', true),
       ('Alpha Industries', 'bebr1@mail.ru', NULL, true),
       ('Beta Corporation', 'bebr1@mail.ru', 'Treat your tired feet to a fiddle-dee-dee massage, a whimsical journey to relaxation.', true),
       ('Gamma Co.', 'SecondOwnerSub', 'Let our squeegee squad bring sparkle and shine to your windows, with a touch of flair.', true),
       ('Delta Enterprises', 'SecondOwnerSub', 'Sip on our brouhaha brew - a concoction of chaos and charm that will tantalize your taste buds.', true),
       ('Omega Ltd.', 'SecondOwnerSub', 'Find balance and flexibility with our wibble wobble yoga sessions - embrace the wobble.', true),
       ('Sigma Corp', 'SecondOwnerSub', 'Get playful with your hair at hokey pokey hair design - where every strand tells a story.', true),
       ('Zeta Corporation', 'SecondOwnerSub', 'Transform your nose with our razzle dazzle rhinoplasty - because ordinary is boring.', true),
       ('Epsilon Enterprises', 'SecondOwnerSub', NULL, true),
       ('Theta Co.', 'bebr1@mail.ru', NULL, true),
       ('Nu Industries', 'bebr1@mail.ru', NULL, true),
       ('Iota Corporation', 'bebr1@mail.ru', 'Discover your true self through the art of sock puppet counseling - whimsical yet profound.', true),
       ('Lambda Ltd.', 'bebr1@mail.ru', NULL, false);
