INSERT INTO business (name, owner_sub, description, active)
VALUES ('ABC Company', 'ownerSub', 'Laugh away your worries with our revolutionary whoopee cushion therapy.', true),
       ('XYZ Corporation', 'ownerSub', 'Experience the thrill of the flip with our flapjack flip service - guaranteed to impress.', true),
       ('123 Enterprises', 'ownerSub', 'Unleash your inner beauty with our mumbo jumbo makeover, where nonsense meets elegance.', true),
       ('Alpha Industries', 'ownerSub', NULL, true),
       ('Beta Corporation', 'ownerSub', 'Treat your tired feet to a fiddle-dee-dee massage, a whimsical journey to relaxation.', true),
       ('Gamma Co.', 'SecondOwnerSub', 'Let our squeegee squad bring sparkle and shine to your windows, with a touch of flair.', true),
       ('Delta Enterprises', 'SecondOwnerSub', 'Sip on our brouhaha brew - a concoction of chaos and charm that will tantalize your taste buds.', true),
       ('Omega Ltd.', 'SecondOwnerSub', 'Find balance and flexibility with our wibble wobble yoga sessions - embrace the wobble.', true),
       ('Sigma Corp', 'SecondOwnerSub', 'Get playful with your hair at hokey pokey hair design - where every strand tells a story.', true),
       ('Zeta Corporation', 'SecondOwnerSub', 'Transform your nose with our razzle dazzle rhinoplasty - because ordinary is boring.', true),
       ('Epsilon Enterprises', 'SecondOwnerSub', NULL, true),
       ('Theta Co.', 'ownerSub', NULL, true),
       ('Nu Industries', 'ownerSub', NULL, true),
       ('Iota Corporation', 'ownerSub', 'Discover your true self through the art of sock puppet counseling - whimsical yet profound.', true),
       ('Lambda Ltd.', 'ownerSub', NULL, false);
