version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: business-pass
      MYSQL_DATABASE: business
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: