version: '3'
services:
  reservapp-business:
    build: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/business-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: business-pass
#      KAFKA-SERVER: localhost:9092
    ports:
      - "8080" # Accessible from outside (no external port assigned yet)
    networks:
      - business-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: business-pass
      MYSQL_DATABASE: business-db
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
    networks:
      - business-network

volumes:
  db:

networks:
  business-network:
