INSERT INTO business (name, owner_sub, active)
VALUES ('ABC Company', '1', true),
       ('XYZ Corporation', '2', true),
       ('123 Enterprises', '3', true),
       ('Alpha Industries', '4', true),
       ('Beta Corporation', '5', true),
       ('Gamma Co.', '6', true),
       ('Delta Enterprises', '7', true),
       ('Omega Ltd.', '8', true),
       ('Sigma Corp', '9', true),
       ('Zeta Corporation', '1', true),
       ('Epsilon Enterprises', '2', true),
       ('Theta Co.', '3', true),
       ('Nu Industries', '4', true),
       ('Iota Corporation', '4', true),
       ('Lambda Ltd.', '2', false);
