@startuml
skinparam sequenceMessageAlign center
autoactivate on

participant Клиент
participant Сервер
participant "Хранилище данных" as Хранилище
participant "Очередь сообщений" as Сообщения

note right Клиент
Сущности (бизнес, сервис, персонал и т.д.)
в приложении не удаляются, а помечаются
неактивными (аттрибут Активно)
end note
Клиент -> Сервер: Запрос на изменение аттрибута Активно сущности \nс Access Token
note over Сервер
Использование пользователя
из Access Token в качестве текущего
end note
note over Сервер: Проверка владения сущностью текущим пользователем
alt Проверки успешны
    note over Сервер: Синхронизация доступа
    Сервер -> Хранилище: Поиск сущности
    return Найденная сущность
    Сервер -> Хранилище: Изменения аттрибута Активно
    return
    Сервер -> Сообщения: Опубликовать сообщение о изменении активности сущности
    return
    return
else Проверки не пройдены
    Сервер --> Клиент: Ошибка авторизации
end
@enduml