@startuml
skinparam sequenceMessageAlign center
autoactivate on

participant Клиент
participant Сервер
participant "Хранилище данных" as Хранилище

Клиент -> Сервер: Запрос на создание\nброни для сотрудника\n с Access Token
note over Сервер
Использование пользователя
из Access Token в качестве текущего
end note
note over Сервер: Проверка валидности токена и существующих прав доступа
alt Валидация успешна
    note over Сервер: Поиск указанного окна для бронирования
    alt Окно для бронирования найдено
        note over Сервер: Проверка наличия мест
        alt Достаточно мест
            note over Сервер: Проверка пересечений с другими бронями
            alt Нет пересечений
                Сервер -> Хранилище: Сохранить новую бронь
                return Сохраненная бронь
                return Сохраненная бронь
            else Есть пересечения
                Сервер --> Клиент: Ошибка пересечения бронирования
            end
        else Недостаточно мест
            Сервер --> Клиент: Ошибка бронирования
        end
    else Окно для бронирования не найдено
        Сервер --> Клиент: Ошибка бронирования
    end
else
    Сервер --> Клиент: Ошибка авторизации
end
@enduml