@startuml
skinparam sequenceMessageAlign center
autoactivate on

participant Клиент
participant Сервер
participant "Хранилище данных" as Хранилище
participant "Очередь сообщений" as Сообщения
Клиент -> Сервер: Запрос на создание услуги\nс Access Token
note over Сервер
Использование пользователя
из Access Token в качестве текущего
end note
note over Сервер: Проверка владения бизнесом текущим пользователем
alt Проверки успешны
    note over Сервер: Синхронизация доступа
    Сервер -> Хранилище: Поиск бизнеса
    return Найденный бизнес
    Сервер -> Хранилище: Сохранить услугу
    return Сохранённая услуга
    Сервер -> Сообщения: Уведомить о новой услуге
    return
    deactivate Сервер
    Сервер --> Клиент: Созданная услуга
else Проверки не пройдены
    Сервер --> Клиент: Ошибка авторизации
end
@enduml