@startuml
skinparam sequenceMessageAlign center
autoactivate on

participant Клиент
participant Сервер
participant "Хранилище данных" as Хранилище

Клиент -> Сервер: Запрос на приглашение пользователя\nв качестве персонала в бизнес\nс Access Token
note over Сервер
Использование пользователя
из Access Token в качестве текущего
end note
note over Сервер: Проверка владения бизнесом текущим пользователем
alt Проверки успешны
    note over Сервер: Синхронизация доступа
    note over Сервер: Проверка отсутствия такого персонала, приглашения\nи существования пользователя
    alt Проверки успешны
        Сервер -> Хранилище: Сохранить приглашение
        return Сохранённое приглашение
        deactivate Сервер
        Сервер --> Клиент: Созданное приглашение
    else Проверки не пройдены
        Сервер --> Клиент: Ошибка приглашения
    end
else Проверки не пройдены
    Сервер --> Клиент: Ошибка авторизации
end
@enduml