@startuml
skinparam sequenceMessageAlign center
autoactivate on

participant Клиент
participant Сервер
participant "Хранилище данных" as Хранилище
participant "Уведомление персонала" as Уведомление

Клиент -> Сервер: Запрос на ответ на приглашение\nс Access Token
note over Сервер
Использование пользователя
из Access Token в качестве текущего
end note

note over Сервер: Проверка на соответствие текущего пользователя и приглашённого
alt Текущий пользователь - Приглашённый

    note over Сервер: Синхронизация доступа
    Сервер -> Хранилище: Поиск приглашения
    return Найденное приглашение
    note over Сервер: Проверка статуса приглашения
    alt Статус приглашения - Ожидание
       Сервер -> Хранилище: Обновить статус приглашения
       return Обновлённое приглашение
        note over Сервер: Проверка статуса ответа на приглашение
       alt Приглашение принято
            Сервер -> Уведомление: Уведомить о новом персонале
            return
        end
        return
    else Статус приглашения не Ожидание
        Сервер --> Клиент: Ошибка недопустимого статуса приглашения
    end
else Текущий пользователь - Не приглашённый
    Сервер --> Клиент: Ошибка авторизации
end
@enduml