version: '4.27'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: accounts-app-password
      MYSQL_DATABASE: accounts-app
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: