spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      authorizationserver:
        issuer: http://accounts:8081/accounts/api-v1 # TODO: Hardcoded
        client:
          reservapp-api:
            registration:
              client-id: reservapp-api
              client-secret: '{bcrypt}$2a$10$/4UfsnNhx.Q6w8Xnarv5/eAx0aXkrgmfAFzsOiGBsstKdy.EhTTP2' # TODO: Hide
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://gateway:8080/login/oauth2/code/spring # Gateway
              scopes:
                - openid
      resourceserver:
        jwt:
          issuer-uri: http://accounts:8081/accounts/api-v1 # TODO: Hardcoded

server:
  http2:
    enabled: true
  servlet:
    context-path: /accounts/api-v1
  port: 8081 # TODO: Hardcoded

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: '/actuator'