spring:
  profiles:
    active: @spring.profiles.active@
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA-SERVER:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # TODO: Hardcoded

business:
  updates:
    email-update-topic: ${EMAIL-UPDATE-TOPIC:account-email-update-topic}
    account-create-topic: ${ACCOUNT-CREATE-TOPIC:account-create-topic}

server:
  http2:
    enabled: true
  servlet:
    context-path: /business/api-v1
  port: 8082 # TODO: Hardcoded