INSERT INTO business (id, owner_sub, active)
VALUES (1, '1', true),
       (2, '2', true),
       (3, '3', true),
       (4, '4', true),
       (5, '5', true),
       (6, '6', true),
       (7, '7', true),
       (8, '8', true),
       (9, '9', true),
       (10, '1', true),
       (11, '2', true),
       (12, '3', true),
       (13, '4', true),
       (14, '4', true),
       (15, '2', false);
