version: '4.27'
services:
  business-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: services-pass
      MYSQL_DATABASE: services-db
    ports:
      - "3306:3306"
    volumes:
      - services-db-data:/var/lib/mysql

volumes:
  services-db-data:
